# Generated by Django 3.1.6 on 2021-02-18 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_movement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
